article/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "article"

urlpatterns = [
    path('dashboard/', views.dashboard, name="dashboard" ),
    path('addarticle/', views.addarticle, name="addarticle"),
    path('article/<int:id>', views.detail, name="detail"),
    path('delete/<int:id>',views.delete,name="delete"),
    path('update/<int:id>',views.update,name="update"),
    path('',views.articles,name="articles"),
    path('comment/<int:id>',views.addComment,name="comment"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from article import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name="index"), #'/' konulursa hata verir. 
    path('about/', views.about, name="about"),
    path('detail/<int:id>', views.detail,name="detail"),
    path('articles/',include("article.urls")), #articles'tan sonra article içerisinde oluşturulan urls dosyasına bakarak devam etmesini söyler.
    path('user/',include("user.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.

class Article(models.Model):
    author = models.ForeignKey("auth.User",on_delete = models.CASCADE,verbose_name="Yazar")
    title = models.CharField(max_length=50,verbose_name="Başlık")
    content = RichTextField(verbose_name="İçerik")
    created_date = models.DateTimeField(auto_now_add=True,verbose_name="Oluşturulma Tarihi")
    article_image = models.FileField(blank=True,null=True,verbose_name="Makale Görseli")
    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['-created_date']

class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete=models.CASCADE,verbose_name="Makale",related_name="comments")
    comment_author = models.CharField(max_length=50,verbose_name="Yazan")
    comment_content = models.CharField(max_length=144,verbose_name="Yorum")
    comment_date = models.DateTimeField(auto_now_add=True,verbose_name="Tarih")
    def __str__(self):
        return self.comment_content
    
    class Meta:
        ordering = ['-comment_date']

article/forms.py
from django import forms
from .models import Article
class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title","content","article_image"]

article/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404,reverse
from .forms import ArticleForm
from django.contrib import messages
from .models import Article, Comment
from django.contrib.auth.decorators import login_required
# Create your views here.
def index(request):
    return render(request,"index.html")

def about(request):
    return render(request,"about.html")

def detail(request,id):
    #article = Article.objects.filter(id=id).first()
    article = get_object_or_404(Article,id=id)
    comments = article.comments.all()
    return render(request,"detail.html",{"article":article,"comments":comments})

@login_required(login_url = "user:login")
def dashboard(request):
    articles = Article.objects.filter(author=request.user)
    return render(request,"dashboard.html",{"articles":articles})

@login_required(login_url = "user:login")
def addarticle(request):
    form = ArticleForm(request.POST or None,request.FILES or None)

    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        messages.add_message(request,messages.SUCCESS,"Makale başarı ile kaydedildi.")
        return redirect("article:dashboard")
    context = {
        "form" : form
    }
    return render(request,"addarticle.html",context)

@login_required(login_url = "user:login")
def update(request,id):
    article = get_object_or_404(Article,id=id)
    form = ArticleForm(request.POST or None,request.FILES or None,instance=article)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        messages.add_message(request,messages.SUCCESS,"Makale başarı ile güncellendi.")
        return redirect("article:dashboard")
    return render(request,"update.html",{"form":form})

@login_required(login_url = "user:login")
def delete(request,id):
    article = get_object_or_404(Article,id=id)
    article.delete()
    messages.add_message(request,messages.SUCCESS,"Makale başarı ile silindi.")
    return redirect("article:dashboard")

def articles(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(title__contains = keyword)
        return render(request,"articles.html",{"articles":articles})
    articles = Article.objects.all()
    return render(request,"articles.html",{"articles":articles})

def addComment(request,id):
    article = get_object_or_404(Article,id=id)
    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")

        newComment = Comment(comment_author=comment_author,comment_content=comment_content)
        newComment.article = article
        newComment.save()
    return redirect(reverse("article:detail",kwargs={"id":id}))

templates/about.html
{% extends "layout.html" %}

{% block body %}
<h3>Hakkımda</h3>
<hr>
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
<hr>
{% endblock body %}

templates/addarticle.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}
{% block body %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Makale Oluştur</h3>
        <hr>
        <form method = "POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Kaydet</button>
        </form>
    </div>
</div>

{% endblock body %}

templates/articles.html
{% extends "layout.html" %}

{% block body %}

<h3>Makaleler</h3>
<hr>
        <form >
            {% csrf_token %}
            <input type="text" name="keyword" class="input-sm" maxlength="64" placeholder="Ara">
            <button type="submit" class="btn btn-danger ">Ara</button>
        </form>
{% if articles %}

{% for article in articles %}
<!-- Page content-->
    <div class="col-md-15 offset-md-3">
        <div class="container mt-5">
            <div class="row">
                <div class="col-lg-8">
                    <!-- Post content-->
                    <article>
                        <!-- Post header-->
                        <header class="mb-4">
                            <!-- Post title-->
                            <a href="{% url 'article:detail' article.id %}"><h2 class="fw-bolder mb-1">{{article.title}}</h2></a>
                            <!-- Post meta content-->
                            <div class="text-muted fst-italic mb-2">{{article.created_date}}</div>
                            <p class="lead">{{article.author}}</p>
                            <hr>
                        </header>
                        <!-- Preview image figure-->
                        {% if article.article_image %}
                        <a href="{% url 'article:detail' article.id %}"><figure class="mb-4"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt="..." /></figure></a>
                        {% else %}
                        {% endif %}
                        <!-- Post content-->
                        <section class="mb-5">
                            <p class="fs-5 mb-4">{{article.content|safe|truncatewords:30}}</p>
                            <a href="{% url 'article:detail' article.id %}" class = "btn btn-danger" style="float:right">Devamını Oku</a>
                            <hr>
                        </section>
                    </article>
                </div>
            </div>
        </div>
    </div>
{% endfor %}
{% else %}
<div class="alert alert-danger">Herhangi bir makale bulunmamaktadır.</div>
{% endif %}

{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}

{% block body %}

<h3>Kontrol Paneli</h3>
<hr>
<p>
Hoş Geldiniz, <small>{{request.user.username}}</small>
</p>
<hr>
<a href = "{% url 'article:addarticle' %}" class="btn btn-danger" >Makale Ekle</a>
<hr>
{% if articles %}


<table class="table">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Başlık</th>
      <th scope="col">Yazar</th>
      <th scope="col">Tarih</th>
      <th scope="col">Güncelle</th>
      <th scope="col">Sil</th>
    </tr>
  </thead>
  <tbody>

    {% for article in articles  %}
        <tr>
            <th scope="row">{{article.id}}</th>
            <td><a href="{% url 'article:detail' article.id %}">{{article.title}}</a></td>
            <td>{{article.author.username}}</td>
            <td>{{article.created_date}}</td>
            <td><a href="{% url 'article:update' article.id %}" class="btn btn-danger">Güncelle</a></td>
            <td><a href="{% url 'article:delete' article.id %}" class="btn btn-danger">Sil</a></td>
            
        </tr>
    {% endfor %}
    <!--<tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
      <td>@mdo</td>
    </tr>-->

  </tbody>
</table>
{% else %}
<div class = "alert alert-danger">Henüz bir makaleniz bulunmuyor.</div>
{% endif %}

{% endblock body %}

templates/detail.html
{% extends "layout.html" %}

{% block body %}

<!-- Page content-->
        <div class="container mt-5">
            <div class="row">
                <div class="col-lg-8">
                    <!-- Post content-->
                    <article>
                        <!-- Post header-->
                        <header class="mb-4">
                            <!-- Post title-->
                            <h3 class="fw-bolder mb-1">{{article.title}}</h3>
                            <!-- Post meta content-->
                            <div class="text-muted fst-italic mb-2">{{article.created_date}}</div>
                            <p class="lead">{{article.author}}</p>
                            <hr>
                        </header>
                        <!-- Preview image figure-->
                        {% if article.article_image %}
                        <figure class="mb-4"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt="..." /></figure>
                        {% else %}
                        {% endif %}
                        <!-- Post content-->
                        <section class="mb-5">
                            <p class="fs-5 mb-4">{{article.content|safe}}</p>
                        </section>

                        <section class="mb-5">
                            <div class="card bg-light">
                                <div class="card-body">
                                    <!-- Comment form-->
                                    <form action = "{% url 'article:comment' article.id %}" method="POST">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            <label for="formGroupExampleInput">İsim</label>
                                            <input name = "comment_author" type="text" class="form-control">                                        
                                        </div>
                                        <div class="form-group">
                                            <label for="formGroupExampleInput">Yorum</label>
                                            <textarea name="comment_content" class="form-control" cols="30" rows="3"></textarea>                                     
                                        </div>
                                        <button type="Submit" class="btn btn-danger">Ekle</button>
                                    </form>
                                    
                        </section>
                        {% if comments %}
                        {% for comment in comments %}
                        <section class="mb-5">
                        <div class="card bg-light">
                            <div class="card-body">
                                <div class="d-flex">
                                    <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                    <div class="ms-3">
                                        <div class="fw-bold">{{comment.comment_author}}</div>
                                                {{comment.comment_date}}
                                                <br>
                                                {{comment.comment_content}}
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                        {% else %}
                        <div class="alert alert-danger">Yorum bulunmamaktadır.</div>
                        {% endif %}
                    </article>
                </div>
            </div>
        </div>

{% endblock body %}

templates/index.html
{% extends "layout.html" %}

{% block body %}

<div class="jumbotron text-center">
    <h3>OGURKANU Bloğuna hoş geldiniz.</h3>
    <p>Bu blogta CBS sektörüne dair her şeyi paylaşabilirsiniz.</p>
</div>

<p>

{% if request.user.is_authenticated %}
    Giriş yapılmış, {{request.user.username}}

{% else %}
    Giriş Yapılmamış
{% endif %}

</p>

{% endblock body %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OGU Blog</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>

    {% include "includes/navbar.html" %}

    <div class = "container" style = "margin-top : 100px; margin-bottom: 100px;">

        {% if messages %}
        
            {% for message in messages %}
            <div{% if message.tags %} class="alert alert-{{message.tags}}"{% endif %}>{{ message }}</div>
            {% endfor %}
        
        {% endif %}    
        {% block body %}
        
        {% endblock body %}
    </div>

    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.6.3.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
</body>
</html>

templates/login.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}

{% block body %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Giriş Yap</h3>
        <hr>
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <br>
            <button type = "submit" class= "btn btn-danger">Giriş Yap</button>
        </form>
    </div>
</div>
{% endblock body %}

templates/register.html
{% extends "layout.html" %}

{% load crispy_forms_tags %}

{% block body %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Kayıt Ol</h3>
        <hr>
        <form method = "POST" >
            {% csrf_token %}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Kayıt Ol</button>
        </form>
    </div>
</div>
{% endblock body %}

templates/update.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}
{% block body %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Makale Güncelle</h3>
        <hr>
        <form method = "POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Kaydet</button>
        </form>
    </div>
</div>

{% endblock body %}